name: build

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-26.04
            arch: x86_64
          - os: ubuntu-26.04-arm
            arch: aarch64
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: build-image
        run: |
          pushd "$(mktemp -d)"
          curl -f -L https://github.com/haskell-wasm/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          podman build \
            --pull \
            --tag rust:alpine-mimalloc \
            .
          popd

      - name: build
        run: |
          podman run \
            --init \
            --rm \
            --volume $PWD:/workspace \
            --workdir /workspace \
            rust:alpine-mimalloc \
            ./build.sh

          MIMALLOC_VERBOSE=1 ./bin/wasm-component-ld --help
          MIMALLOC_VERBOSE=1 ./bin/wasm-tools --version
          MIMALLOC_VERBOSE=1 ./bin/wasmi_cli --version
          MIMALLOC_VERBOSE=1 ./bin/wasmtime --version
          MIMALLOC_VERBOSE=1 ./bin/wit-bindgen --version
          MIMALLOC_VERBOSE=1 ./bin/wizer --version

          file ./bin/wasm-component-ld
          file ./bin/wasm-tools
          file ./bin/wasmi_cli
          file ./bin/wasmtime
          file ./bin/wit-bindgen
          file ./bin/wizer

          mkdir wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux
          mv bin wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux
          tar \
            --sort=name \
            --owner=0 --group=0 --numeric-owner \
            --use-compress-program="zstd --ultra -22 --threads=0" \
            -cf wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux.tar.zst \
            wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux
          path: wasm-tools-${{ github.ref_name }}-${{ matrix.arch }}-linux.tar.zst

  build-darwin:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-26-intel
            arch: x86_64
          - os: macos-26
            arch: aarch64
    env:
      MACOSX_DEPLOYMENT_TARGET: "14.0"
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: install-deps
        run: |
          rustup update
          rustup target add ${{ matrix.arch }}-apple-darwin

      - name: build
        run: |
          ./build.sh --target ${{ matrix.arch }}-apple-darwin

          file ./bin/wasm-component-ld
          file ./bin/wasm-tools
          file ./bin/wasmi_cli
          file ./bin/wasmtime
          file ./bin/wit-bindgen
          file ./bin/wizer

          mkdir wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}
          mv bin wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}
          tar \
            --use-compress-program="zstd --ultra -22 --threads=0" \
            -cf wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}.tar.zst \
            wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}
          path: wasm-tools-${{ github.ref_name }}-darwin-${{ matrix.arch }}.tar.zst

  release:
    if: github.event_name == 'push'
    needs:
      - build-linux
      - build-darwin
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: publish-release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release create ${{ github.ref_name }} wasm-tools-*.tar.zst \
            --title ${{ github.ref_name }} \
            --notes-file /dev/null \
            --latest \
            --verify-tag
